### ISSUE TITLE
error log.Format

### ISSUE THREAD

**Issue by daleangus** [leprosus/golang-log#1]
I am getting an error at this line https://github.com/leprosus/golang-log/blob/9d20a0b2a19c4bdaad42ef9a9fdbad250c6d78c4/log.go#L119

`panic: sync/atomic: store of inconsistently typed value into Value`

My code is
```
	log.Format(func(level int, line string, message string) string {
		return message
	})
```

What am I doing wrong? Simply followed the example in the README.

**Comment by leprosus** [comment]
Hello daleangus,

I am sorry for a long answer.
I have fixed your case.
